FROM gradle:8 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN ["gradle", "build", "--no-daemon"]

FROM amazoncorretto:21-alpine

# Install Powershell
RUN ["apk", "add", "ca-certificates", "less", "ncurses-terminfo-base", "krb5-libs", "libgcc", "libintl", "libstdc++", "tzdata", "userspace-rcu", "zlib", "icu-libs", "curl"]
RUN ["apk", "-X", "https://dl-cdn.alpinelinux.org/alpine/edge/main", "add", "--no-cache", "lttng-ust"]
RUN ["curl", "-L", "https://github.com/PowerShell/PowerShell/releases/download/v7.4.1/powershell-7.4.1-linux-musl-x64.tar.gz", "-o", "/tmp/powershell.tar.gz"]
RUN ["mkdir", "-p", "/opt/microsoft/powershell/7"]
RUN ["tar", "zxf", "/tmp/powershell.tar.gz", "-C", "/opt/microsoft/powershell/7"]
RUN ["chmod", "+x", "/opt/microsoft/powershell/7/pwsh"]
RUN ["ln", "-s", "/opt/microsoft/powershell/7/pwsh", "/usr/bin/pwsh"]
RUN ["pwsh", "-Command", "Install-Module", "ExchangeOnlineManagement", "-Force"]

COPY powershell /app/
COPY --from=build /home/gradle/src/build/libs/onboarding-0.0.1-SNAPSHOT.jar /app/onboarding-0.0.1-SNAPSHOT.jar

WORKDIR /app
EXPOSE 80

ENTRYPOINT ["java", "-jar","/app/onboarding-0.0.1-SNAPSHOT.jar"]